[build]
builder = "NIXPACKS"
buildCommand = "npm ci && cd packages/backend && npm run build"

[deploy]
startCommand = "cd packages/backend && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"

[env]
NODE_ENV = "production" 